apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      tolerations:
        {{- range .Values.tolerations }}
        - key: {{ .key }}
          operator: {{ .operator }}
          effect: {{ .effect }}
        {{- end }}
      nodeSelector: 
      {{- range $key, $val := .Values.nodeSelector}}
        {{$key}}: {{$val}}
      {{- end }}
      containers:
        - name: my-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
