image:
  repository: gcr.io/jeeng-projects/nginx-hello-world
  tag: 1.0

replicas: 10

resources:
  requests:
    cpu: 1
    memory: 2Gi

nodeSelector:
  instane_type: small

tolerations:
  - key: "jeeng-assignments"
    operator: "Exists"
    effect: "NoSchedule"
  
serviceAccountName: jeeng-assignments-sa
